export const Icons = {
  direction_left: require('../assets/direction_left.png'),
  user: require('../assets/user.png'),
  gmail_fill: require('../assets/gmail_fill.png'),
  country_code: require('../assets/country_code.png'),
  google: require('../assets/google.png'),
  AppLogo: require('../assets/logo.png'),
  doodle: require('../assets/doodle.png'),
  eye: require('../assets/eye.png'),
  closed_eye: require('../assets/eye_closed.png'),
  email_shade: require('../assets/gmail_shade.png'),
  user_shade: require('../assets/user_dark.png'),
  country: require('../assets/country.png'),
  mobile: require('../assets/mobile.png'),
  Home: require('../assets/Home.png'),
  Home_Focused: require('../assets/Home_Focused.png'),
  profile: require('../assets/user.png'),
  profile_focused: require('../assets/profile_focused.png'),
  orders: require('../assets/orders.png'),
  orders_focused: require('../assets/orders_focused.png'),
  orders_animated: require('../assets/orders_animated.gif'),
  Favourites: require('../assets/Favouriti.png'),
  Favorites_Focused: require('../assets/Favority_Focoused.png'),
  settings: require('../assets/settings.png'),
  settings_focused: require('../assets/settings_focused.png'),
};
