export const Icons = {
  direction_left: require('../assets/direction_left.png'),
  user: require('../assets/user.png'),
  gmail_fill: require('../assets/gmail_fill.png'),
  country_code: require('../assets/country_code.png'),
  google: require('../assets/google.png'),
  AppLogo: require('../assets/logo.png'),
  doodle: require('../assets/doodle.png'),
  eye: require('../assets/eye.png'),
  closed_eye: require('../assets/eye_closed.png'),
  email_shade: require('../assets/gmail_shade.png'),
  user_shade: require('../assets/user_shade.png'),
  country: require('../assets/country.png'),
  mobile: require('../assets/mobile.png'),
};
